name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "the job automatically triggered by a ${{ github.event_name }} event"
      - uses: actions/checkout@v1
      - name: list files in the repo
        run: ls ${{ github.workspace }}
