# label workflow
name: deploy vercel

# executes workflows that are defined with the on key
on:
  push:
    branches:
      - master
      - staging
      - development
      - uat

jobs:
  vercel:
    name: "Deploy front-end with vercel"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: instal dependencies
        uses: actions/setup-node@v1

      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${VERCEL_TOKEN} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.vercel_token }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
