# label workflow
name: deploy vercel

# executes workflows that are defined with the on key
on:
  push:
    branches:
      - master
      - staging
      - development
      - uat

jobs:
  deploy-vercel:
    name: "deploy-vercel"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: instal dependencies
        uses: actions/setup-node@v1

      - name: "Deploy to Vercel"
        run: |
          prodRun=""
          if [[ ${GITHUB_REF} == "refs/heads/main" ]]; then
            prodRun="--prod"
          fi

          npx vercel --token ${{ secrets.vercel_token }} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.vercel_token }}
          VERCEL_PROJECT_ID: ${{ secrets.vercel_project_id }}
          VERCEL_ORG_ID: ${{ secrets.vercel_org_id }}
